Document: aiodns
Title: Debian aiodns Manual
Author: <insert document author here>
Abstract: This manual describes what aiodns is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/aiodns/aiodns.sgml.gz

Format: postscript
Files: /usr/share/doc/aiodns/aiodns.ps.gz

Format: text
Files: /usr/share/doc/aiodns/aiodns.text.gz

Format: HTML
Index: /usr/share/doc/aiodns/html/index.html
Files: /usr/share/doc/aiodns/html/*.html
